name: 'Setup Linode CLI'
description: 'Install the Linode CLI in a GitHub Actions environment.'
author: 'Akamai <developers@linode.com>'
branding:
  icon: 'server'
  color: 'orange'
inputs:
  token:
    description: 'The Linode API Personal Access Token to authenticate with.'
  version:
    description: 'The Linode CLI version to install.'
    default: latest
  optional-deps:
    description: 'Whether optional Linode CLI dependencies should be installed.'
    default: false
  setup-python:
    description: 'If true, Python will automatically be installed on the runner.'
    default: true
  upgrade:
    description: 'If true, Linode CLI and its dependencies will be automatically upgraded. (--upgrade)'
    default: true
runs:
  using: 'composite'
  steps:
    - name: Mask the input token
      shell: bash
      run: echo "::add-mask::${{ inputs.token }}"

    - name: Setup Python 3
      uses: actions/setup-python@v4
      if: ${{ inputs.setup-python == 'true' }}
      with:
        python-version: '3.x'

    - name: Determine CLI install extension
      id: determine_install_ext
      shell: bash
      run: |
        EXTENSION=""

        if [ "$OPTIONAL_DEPS" == "true" ]
        then
          EXTENSION="[obj]"
        fi
        
        if [ "$VERSION" != "latest" ]
        then
          EXTENSION="${EXTENSION}==${VERSION}"
        fi
        
        echo "version_extension=${EXTENSION}" >> $GITHUB_ENV
      env:
        VERSION: ${{ inputs.version }}
        OPTIONAL_DEPS: ${{ inputs.optional-deps }}

    - name: Install the Linode CLI
      run: pip3 install ${{ inputs.upgrade && '--upgrade ' || '' }}linode-cli${{ env.version_extension }}
      shell: bash

    - name: Expose the Linode Token to the runner environment
      if: ${{ inputs.token != '' }}
      shell: bash
      run: echo "LINODE_CLI_TOKEN=${{ inputs.token }}" >> "$GITHUB_ENV"

    - name: Validate the CLI is installed
      if: ${{ inputs.token != '' }}
      run: linode-cli --version
      shell: bash